clc
close all
clearvars -except indexFile folder Assessment*

fprintf('\nWelcome to the RunMFiles! Thanks for choosing Umur''s TA emporium! \n')
fprintf('  A couple of friendly reminders:\n')
fprintf('   - If you haven''t specified a directory yet (no string named ''folder'' in the workspace) you will be asked to choose \n')
fprintf('     the directory containing the M-Files you want me to run back to back.\n')
fprintf('   - The workspace will be cleared except for a few variables that I need to function between each M-File\n')
fprintf('   - If at any point, you need to stop and take a look at the workspace generated by an M-File, you can stop me with ctrl+c. \n')
fprintf('     As long as you don''t delete the variables named ''folder'' and ''indexFile'', I will pick up where we left off when you run me again.\n')
fprintf('   - If you are assessing FUNCTIONS, you can create a variable named ''AssessmentIsFun'' in the workspace to let me know.\n')
fprintf('     In that case, you need to create a cell array named ''AssessmentInputs'' with each element being an input to the functions.\n')
fprintf('     I will try my best to call each M-File within the directory with the inputs specidied in ''AssessmentInputs''\n')
fprintf('  Now get ready for the ride, brace yourself and PRESS ANY KEY to continue... \n')
pause()
if ~exist('folder')
    folder  = uigetdir;
end
try
    indexStart = indexFile;
catch
    indexStart = 1;
end
list    = dir(fullfile(folder, '*.m'));
n       = length(list);
% editor  = com.mathworks.mlservices.MLEditorServices;
% app=editor.getEditorApplication;
for indexFile=indexStart:n
    file=list(indexFile).name;
    fprintf('\nGetting rid of clear commands...')

    commentClrs(fullfile(folder,file));
end
for indexFile=indexStart:n
    file=list(indexFile).name;
    suppressClears(fullfile(folder,file));
    open(fullfile(folder,file));
    try
        if exist('AssessmentIsFun')
            callString = file(1:end-2);
            callString = [callString, '('];
            for indexInput = 1:length(AssessmentInputs)
                callString = [callString, 'AssessmentInputs{',...
                                num2str(indexInput),'},'];
            end
            callString(end) = ')';
            eval(callString)
        else
            run(fullfile(folder,file));
        end
    catch
        disp('error');
    end
    pause();
%     act=app.getActiveEditor;
%     act.closeNoPrompt;
    act = matlab.desktop.editor.getActive;
    act.closeNoPrompt;

    clc
    close all
    clearvars -except indexFile folder file list n editor app act Assessment*
end
fprintf('\nHooray! That was the last M File in the directory! \n')
fprintf('Now if you want to select a different directory, don''t forget to clear the variables named ''folder'' and ''indexFile''.\n')
fprintf('I hope you had fun... I sure did ^^ \n')
